
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
     "account": "User 3",
     "password": "Optech123"
}

###
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
     "account": "ser 3",
     "fullName": "full name 4",
     "password": "ptech123"
}

